AWSTemplateFormatVersion: '2010-09-09'
Description: Amazon Pinpoint Voice Channel.  This application will place outbound calls triggered by Amazon Pinpoint.  Written in Python3.
Transform: AWS::Serverless-2016-10-31

Parameters:
  PINPOINTLONGCODES:
    Type: String
    Description: Comma delimitted list of Pinpoint Long Codes.

Metadata:
  AWS::ServerlessRepo::Application:
    Name: amazon-pinpoint-voice-channel
    Description: Amazon Pinpoint Voice Channel.  This application will place outbound calls triggered by Amazon Pinpoint.
    Author: Amazon Pinpoint
    SpdxLicenseId: MIT-0
    LicenseUrl: LICENSE
    ReadmeUrl: README.md
    Labels: ['amazon-pinpoint', 'pinpoint', 'custom-channel', 'voice', 'python']
    HomePageUrl: https://aws.amazon.com/pinpoint
    SemanticVersion: 1.0.1
    SourceCodeUrl: https://github.com/aws-samples/amazon-pinpoint-voice-channel

Resources:
  VoiceSQSQueue:
    Type: AWS::SQS::Queue
    DependsOn: "VoiceSQSQueueCMK"
    Properties:
      VisibilityTimeout: 100
      FifoQueue: true
      KmsMasterKeyId:
        Ref: VoiceSQSQueueCMK
      KmsDataKeyReusePeriodSeconds: 600

  PinpointVoiceQueuerFunctionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName:
        Fn::Sub: "${AWS::Region}-PinpointVoiceQueuerFunctionRole"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/service-role/AWSLambdaSQSQueueExecutionRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: PinpointVoiceQueuerPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: WriteSQS
                Effect: Allow
                Action: sqs:SendMessage
                Resource: "*"

  PinpointVoiceChannelFunctionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName:
        Fn::Sub: "${AWS::Region}-PinpointVoiceChannelFunctionRole"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/service-role/AWSLambdaSQSQueueExecutionRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: PinpointVoiceChannelFunctionPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: SendVoiceMessage
                Effect: Allow
                Action: sms-voice:SendVoiceMessage
                Resource: !Sub arn:aws:sms-voice:${AWS::Region}:${AWS::AccountId}:/v1/sms-voice/voice/message
              - Sid: PinpointPutEvents
                Effect: Allow
                Action: mobiletargeting:PutEvents
                Resource: !Sub arn:${AWS::Partition}:mobiletargeting:${AWS::Region}:${AWS::AccountId}:*
              - Sid: DecryptMessage
                Effect: Allow
                Action: ['kms:Decrypt', 'kms:GenerateDataKey']
                Resource: "*"

  VoiceSQSQueueCMK:
    Type: "AWS::KMS::Key"
    DependsOn:
      - "PinpointVoiceQueuerFunctionRole"
      - "PinpointVoiceChannelFunctionRole"
    Properties:
      Description: 'CMK used for encryption/decryption of queue VoiceSQSQueue.'
      EnableKeyRotation: true
      KeyPolicy:
        Version: '2012-10-17'
        Id: VoiceSQSQueueCMK'
        Statement:
          -
            Sid: 'Allow administration of the key'
            Effect: Allow
            Principal:
              AWS:
                - Fn::Sub: 'arn:${AWS::Partition}:iam::${AWS::AccountId}:root'
            Action:
              - 'kms:Create*'
              - 'kms:Describe*'
              - 'kms:Enable*'
              - 'kms:List*'
              - 'kms:Put*'
              - 'kms:Update*'
              - 'kms:Revoke*'
              - 'kms:Disable*'
              - 'kms:Get*'
              - 'kms:Delete*'
              - 'kms:ScheduleKeyDeletion'
              - 'kms:CancelKeyDeletion'
            Resource: '*'
          -
            Sid: 'Allow use of the key'
            Effect: Allow
            Principal:
              AWS:
                - Fn::Sub: "arn:${AWS::Partition}:iam::${AWS::AccountId}:role/${AWS::Region}-PinpointVoiceQueuerFunctionRole"
                - Fn::Sub: "arn:${AWS::Partition}:iam::${AWS::AccountId}:role/${AWS::Region}-PinpointVoiceChannelFunctionRole"
            Action:
              - 'kms:Encrypt'
              - 'kms:Decrypt'
              - 'kms:ReEncrypt*'
              - 'kms:GenerateDataKey*'
              - 'kms:DescribeKey'
            Resource: '*'

  PinpointVoiceQueuerFunction:
    Type: AWS::Serverless::Function
    DependsOn: "VoiceSQSQueueCMK"
    Properties:
      FunctionName: AmazonPinpointVoiceChannel
      CodeUri: voicequeuer/
      Handler: app.lambda_handler
      Runtime: python3.7
      Timeout: 60
      Environment:
        Variables:
          SQS_QUEUE_URL: !Ref VoiceSQSQueue
          PINPOINT_LONG_CODES: !Ref PINPOINTLONGCODES
      Role: !GetAtt PinpointVoiceQueuerFunctionRole.Arn


  PinpointVoiceChannelFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: AmazonPinpointVoiceChannel-backgrounprocessor
      CodeUri: pinpointvoice/
      Handler: app.lambda_handler
      Runtime: python3.7
      Timeout: 45
      ReservedConcurrentExecutions: 5
      Events:
        VoiceSQSQueueEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt VoiceSQSQueue.Arn
            BatchSize: 10
      Role: !GetAtt PinpointVoiceChannelFunctionRole.Arn


  PinpointInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref PinpointVoiceQueuerFunction
      Principal: !Sub pinpoint.${AWS::Region}.amazonaws.com
      SourceArn: !Sub arn:${AWS::Partition}:mobiletargeting:${AWS::Region}:${AWS::AccountId}:apps/*

Outputs:
  PinpointVoiceQueuerFunction:
    Description: "A function invoked by an Amazon Pinpoint Campaign or Journey that will place an outbound call to a user"
    Value: !GetAtt PinpointVoiceQueuerFunction.Arn
